/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrthodontieRouteImport } from './routes/orthodontie'
import { Route as IndexRouteImport } from './routes/index'

const OrthodontieRoute = OrthodontieRouteImport.update({
  id: '/orthodontie',
  path: '/orthodontie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orthodontie': typeof OrthodontieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orthodontie': typeof OrthodontieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orthodontie': typeof OrthodontieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/orthodontie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/orthodontie'
  id: '__root__' | '/' | '/orthodontie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrthodontieRoute: typeof OrthodontieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orthodontie': {
      id: '/orthodontie'
      path: '/orthodontie'
      fullPath: '/orthodontie'
      preLoaderRoute: typeof OrthodontieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrthodontieRoute: OrthodontieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
